package codeanalyzetools
import java.util.Locale

plugins.apply(JacocoPlugin::class)

configure<JacocoPluginExtension> {
    toolVersion = "0.8.11"
}

tasks.withType<Test> {
    configure<JacocoTaskExtension> {
        isIncludeNoLocationClasses = false
        excludes = listOf("jdk.internal.*")
    }
}

val fileFilter =
    listOf(
        "**/R.class",
        "**/R.*",
        "**/*R.class",
        "**/*R.*",
        "**/R\$*.class",
        "**/R\$*.styleable",
        "**/R.styleable",
        "**/BuildConfig.*",
        "**/Manifest*.*",
        "**/*Adapter*.*",
        "**/*Test*.*",
        "android/**/*.*",
        "**/android/**/*.*",
        "**/*Fragment.*",
        "**/*Fragment*.*",
        "**/*Activity.*",
        "**/*Activity*.*",
        "**/*\$Lambda$*.*", // Jacoco can not handle several "$" in class name.
        "**/*\$inlined$*.*", // Kotlin specific, Jacoco can not handle several "$" in class name.
        // adapters generated by moshi
        "**/*JsonAdapter.*",
        "**/*Companion*.*",
        "**/*Module*.*",
        "**/*Dagger*.*",
        "**/*Hilt*.*",
        "**/*MembersInjector*.*",
        "**/*_MembersInjector.class",
        "**/*_Factory*.*",
        "**/*_Provide*Factory*.*",
        "**/*Extensions*.*",
        // data binding
        "**/*DataBinding*.*",
        "**/*Directions*.*",
        "**/*Args*.*",
        "android/databinding/**/*.class",
        "**/android/databinding/*Binding.class",
        "**/android/databinding/*",
        "**/androidx/databinding/*",
        "**/databinding/*",
        "**/BR.*",
        "**/*BR*.*",
        // sealed and data classes
        "**/BR.*",
        "**/DataBinder*.class",
        "**/*$Result.*",
        "**/*$Result\$*.*",
        "**/*App.*",
        "**/*Application.*",
        "**/*Activity.*",
        "**/*Fragment.*",
        "**/*Destination*.*",
        "**/*Screen*.*",
        "**/*Page*.*",
        "**/*Body*.*",
        "**/*Content*.*",
        "**/*View*.*",
        "**/*Row*.*",
        "**/MainInteractionSessionService.class",
        "**/android/*",
        "**/google/*",
        "androidx/**",
        "**/androidx/**/*.*",
        "**/fabric/*.*",
        "**/CrashReportingTree.class",
        "**/*Companion.class",
        "com/ramcosta/**/*.*",
        "**/airbnb/*",
        "**/*_MembersInjector.class",
        "**/Dagger*Component.class",
        "**/Dagger*Component\$Builder.class",
        "**/*Module_*Factory.class",
        "**/hilt_aggregated_deps/*",
        "**/di/**/*.*",
        "**/extension/*.*",
    )

fun retrieveSourceDirectoriesTree(variantName: String): ConfigurableFileCollection {
    return files(
        "${project.projectDir}/src/main/java",
        "${project.projectDir}/src/main/kotlin",
        "${project.projectDir}/src/debug/java",
        "${project.projectDir}/src/debug/kotlin",
        "${project.projectDir}/src/${variantName}/java",
        "${project.projectDir}/src/${variantName}/kotlin",
    )
}

fun retrieveClassDirectoriesTree(variantName: String): ConfigurableFileTree {
    return fileTree(layout.buildDirectory) {
        include(
            "**/classes/**/main/**",
            "**/intermediates/classes/${variantName}/**",
            "**/intermediates/javac/${variantName}/classes/**", // Android Gradle Plugin 3.2.x support.
            "**/tmp/kotlin-classes/${variantName}/**",
        )
        exclude(fileFilter)
    }
}

fun retrieveExecutionDataTree(variantName: String, testTaskName: String): ConfigurableFileTree {
    return fileTree(layout.buildDirectory) {
        include(
            "**/jacoco/$testTaskName.exec",
            "**/outputs/unit_test_code_coverage/${testTaskName}/${testTaskName}.exec",
            "**/outputs/code_coverage/**/*.ec",
            "**/jacoco/jacocoTestReport${variantName.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }}.exec",
            "**/jacoco/${testTaskName}.exec",
            "**/jacoco/test.exec",
        )
    }
}

fun JacocoReportsContainer.reports() {
    xml.required.set(true)
    html.required.set(true)
    xml.outputLocation.set(layout.buildDirectory.file("reports/jacoco/jacocoTestReport/jacocoTestReport.xml"))
    html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/jacocoTestReport/html"))
}

fun JacocoReport.setDirectories(variantName: String, testTaskName: String) {
    println("JacocoReport.setDirectories(variantName: $variantName)")

    val sourceDirectoriesTree = retrieveSourceDirectoriesTree(variantName)
    println("sourceDirectoriesTree: ${sourceDirectoriesTree.count()}")
    sourceDirectories.setFrom(sourceDirectoriesTree)

    val classDirectoriesTree = retrieveClassDirectoriesTree(variantName)
    println("classDirectoriesTree: ${classDirectoriesTree.count()}")
    classDirectories.setFrom(classDirectoriesTree)

    val executionDataTree = retrieveExecutionDataTree(variantName, testTaskName)
    println("executionDataTree: ${executionDataTree.count()}")
    executionData.setFrom(executionDataTree)
}

fun JacocoCoverageVerification.setDirectories(variantName: String, testTaskName: String) {
    println("JacocoCoverageVerification.setDirectories(variantName: $variantName)")

    val sourceDirectoriesTree = retrieveSourceDirectoriesTree(variantName)
    println("sourceDirectoriesTree: ${sourceDirectoriesTree.count()}")
    sourceDirectories.setFrom(sourceDirectoriesTree)

    val classDirectoriesTree = retrieveClassDirectoriesTree(variantName)
    println("classDirectoriesTree: ${classDirectoriesTree.count()}")
    classDirectories.setFrom(classDirectoriesTree)

    val executionDataTree = retrieveExecutionDataTree(variantName, testTaskName)
    println("executionDataTree: ${executionDataTree.count()}")
    executionData.setFrom(executionDataTree)
}

afterEvaluate {
    extensions.findByType(com.android.build.gradle.internal.dsl.BaseAppModuleExtension::class.java)?.run {
        applicationVariants.toList().forEach { variant ->
            val variantName = variant.name
            val testTaskName =
                "test${variantName?.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }}UnitTest"

            println("project: ${project.displayName}; variantName: $variantName")
            println("project: ${project.displayName}; testTaskName: $testTaskName")
            variantName?.let { registerReport(variantName = it, testTaskName = testTaskName) }
        }
    }
    extensions.findByType(com.android.build.gradle.LibraryExtension::class.java)?.run {
        libraryVariants.toList().forEach { variant ->
            val variantName = variant.name
            val testTaskName =
                "test${variantName?.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }}UnitTest"

            println("project: ${project.displayName}; variantName: $variantName")
            println("project: ${project.displayName}; testTaskName: $testTaskName")
            variantName?.let { registerReport(variantName = it, testTaskName = testTaskName) }
        }
    }
}

fun registerReport(variantName: String, testTaskName: String) {
    tasks.register<JacocoReport>("jacoco${variantName.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }}Report") {
        group = "Module's Test Coverage"
        description = "Code coverage report for both Android and Unit tests."
        dependsOn(testTaskName)

        reports { reports() }
        setDirectories(variantName, testTaskName)

        finalizedBy("jacoco${variantName.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }}TestCoverage")

//        doLast {
//            serviceOf<ExecOperations>().exec {
//                commandLine("open", "${layout.buildDirectory.get()}/reports/jacoco/jacocoTestReport/html/index.html")
//            }
//        }
    }

    tasks.register<JacocoCoverageVerification>("jacoco${variantName.replaceFirstChar { if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString() }}TestCoverage") {
        group = "Module's Test Coverage"
        description =
            "Generates coverage ratio(./gradlew jacocoAndroidTestCoverage -PminCoverage=0.0)"
        setDirectories(variantName, testTaskName)
        violationRules {
            isFailOnViolation = true
            rule {
                limit {
                    minimum = "0.0".toBigDecimal()
                }
            }
            rule {
                element = "CLASS"
                includes = listOf("org.gradle")
                limit {
                    counter = "LINE"
                    value = "TOTALCOUNT"
                    minimum = "0.0".toBigDecimal()
                }
            }
        }
    }
}
