package codeanalyzetools

plugins.apply(JacocoPlugin::class)

configure<JacocoPluginExtension> {
    toolVersion = "0.8.11"
}

tasks.withType<Test> {
    configure<JacocoTaskExtension> {
        isIncludeNoLocationClasses = false
        excludes = listOf("jdk.internal.*")
    }
}

val fileFilter =
    listOf(
        "**/R.class",
        "**/R.*",
        "**/*R.class",
        "**/*R.*",
        "**/R\$*.class",
        "**/R\$*.styleable",
        "**/R.styleable",
        "**/BuildConfig.*",
        "**/Manifest*.*",
        "**/*Adapter*.*",
        "**/*Test*.*",
        "android/**/*.*",
        "**/android/**/*.*",
        "**/*Fragment.*",
        "**/*Fragment*.*",
        "**/*Activity.*",
        "**/*Activity*.*",
        "**/*\$Lambda$*.*", // Jacoco can not handle several "$" in class name.
        "**/*\$inlined$*.*", // Kotlin specific, Jacoco can not handle several "$" in class name.
        // adapters generated by moshi
        "**/*JsonAdapter.*",
        "**/*Companion*.*",
        "**/*Module*.*",
        "**/*Dagger*.*",
        "**/*Hilt*.*",
        "**/*MembersInjector*.*",
        "**/*_MembersInjector.class",
        "**/*_Factory*.*",
        "**/*_Provide*Factory*.*",
        "**/*Extensions*.*",
        // data binding
        "**/*DataBinding*.*",
        "**/*Directions*.*",
        "**/*Args*.*",
        "android/databinding/**/*.class",
        "**/android/databinding/*Binding.class",
        "**/android/databinding/*",
        "**/androidx/databinding/*",
        "**/databinding/*",
        "**/BR.*",
        "**/*BR*.*",
        // sealed and data classes
        "**/BR.*",
        "**/DataBinder*.class",
        "**/*$Result.*",
        "**/*$Result\$*.*",
        "**/*App.*",
        "**/*Application.*",
        "**/*Activity.*",
        "**/*Fragment.*",
        "**/*Destination*.*",
        "**/*Screen*.*",
        "**/*Page*.*",
        "**/*Body*.*",
        "**/*Content*.*",
        "**/*View*.*",
        "**/*Row*.*",
        "**/MainInteractionSessionService.class",
        "**/android/*",
        "**/google/*",
        "androidx/**",
        "**/androidx/**/*.*",
        "**/fabric/*.*",
        "**/CrashReportingTree.class",
        "**/*Companion.class",
        "com/ramcosta/**/*.*",
        "**/airbnb/*",
        "**/*_MembersInjector.class",
        "**/Dagger*Component.class",
        "**/Dagger*Component\$Builder.class",
        "**/*Module_*Factory.class",
        "**/hilt_aggregated_deps/*",
        "**/di/**/*.*",
        "**/extension/*.*",
        // checker
        "com/chuckerteam/chucker/**/*.*",
    )

// TODO: You need to declare modules that you want to combine coverage.
val coverModules = "local, model, remote, repository, context," +
    " capabilitiesAgent, contextManager, authenticator" +
    " components, framework," +
    " vaframework," +
    " vfframework," +
    " va, testing, autotest"

// TODO: You need to declared all build variant types whenever you create a new one.
// such as: globalDebug, vfe34Debug, vf8Debug,...
val buildVariants = listOf("globalDebug", "vfe34Debug", "vf8Debug")

fun retrieveMultipleClassDirectoriesTree(project: Project): List<ConfigurableFileTree> {
    val classDirectoriesTree = mutableListOf<ConfigurableFileTree>()
    buildVariants.forEach { buildVariant ->
        classDirectoriesTree.add(
            fileTree(project.layout.buildDirectory) {
                exclude(fileFilter)
                include(
                    "**/classes/**/main/**",
                    "**/intermediates/classes/${buildVariant}/**",
                    "**/intermediates/javac/${buildVariant}/classes/**", // Android Gradle Plugin 3.2.x support.
                    "**/tmp/kotlin-classes/${buildVariant}/**",
                )
            },
        )
    }
    return classDirectoriesTree
}

afterEvaluate {
    tasks.register<JacocoReport>("jacocoMultiCoverage") {
        group = "App's multiple module coverage"
        description = "Generate overall Jacoco coverage report for the debug build."
        reports {
            html.required.set(true)
            xml.required.set(true)
            html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco/multiCoverage/html"))
            xml.outputLocation.set(layout.buildDirectory.file("reports/jacoco/multiCoverage/jacocoTestReport.xml"))
        }

        val coverProjects = subprojects.filter { it.name in coverModules }
        val classDirectoriesTree = mutableListOf<ConfigurableFileTree>()
        coverProjects.forEach {
            classDirectoriesTree.addAll(retrieveMultipleClassDirectoriesTree(it))
        }

        classDirectories.setFrom(classDirectoriesTree)
        val sourceDirectoriesTree = mutableListOf<ConfigurableFileTree>()
        coverProjects.forEach {
            println("buildDir: ${it.layout.buildDirectory.get()}")
            sourceDirectoriesTree.add(
                fileTree(it.layout.buildDirectory) {
                    include(
                        "**/src/**/java/**",
                        "**/src/**/kotlin/**",
                    )
                },
            )
        }

        sourceDirectories.setFrom(sourceDirectoriesTree)
        val executions = mutableListOf<ConfigurableFileTree>()

        coverProjects.forEach {
            executions.add(
                fileTree(it.layout.buildDirectory) {
                    include(
                        "outputs/unit_test_code_coverage/**/*.exec",
                        "outputs/code_coverage/**/*.ec",
                        "jacoco/*.exec",
                    )
                },
            )
        }

        executionData.setFrom(executions)
//        doLast {
//            serviceOf<ExecOperations>().exec {
//                commandLine("open", "build/reports/jacoco/multiCoverage/html/index.html")
//            }
//        }
    }
}
